### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by Mogost** [jazzband/django-pipeline#649]
> Support for the django.core.files.storage.Storage.accessed_time(), created_time(), and modified_time() methods is removed.

> https://docs.djangoproject.com/en/2.0/releases/2.0/

AttributeError: 'PipelineCachedStorage' object has no attribute 'modified_time'

**Comment by peterbe** [comment]
I'm running django-pipeline with Django 2.1. Works perfectly fine. Pretty sure it worked with Django 2.0.8 too.
