### ISSUE TITLE
Cannot import name staticfiles_storage

### ISSUE THREAD

**Issue by fcsonline** [jazzband/django-pipeline#78]
We are working with Django version 1.3.1 and django-pipeline 1.2, and we get an Exception when we include the templatetag compressed.

```
Exception Value:    
'compressed' is not a valid tag library: ImportError raised loading pipeline.templatetags.compressed: cannot import name staticfiles_storage
```

Do you know the reason?
